package com.bbf.spider.mapper;

import com.bbf.spider.Menu;

public interface MenuMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int insert(Menu record);
}
