package com.bbf.spider.mapper;

import com.bbf.spider.Product;

import java.util.List;

public interface ProductMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int insert(Product record);

    List<Product> selectMainSort();
}
